global:
  name: benchmark
  phase: train
  stage: pretrain-vision
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['data/training/scene/scene_train/',
            'data/training/scene/scene_test/'
            ],
    batch_size: 200
  }
  test: {
    roots: ['data/training/scene/scene_val/',
            'data/evaluation/SVT',
            'data/evaluation/SVTP',
            'data/evaluation/CUTE80'],
    batch_size: 200
  }
  charset_path: data/new_benchmark.txt
  data_aug: True
  multiscales: False
  num_workers: 9

training:
  epochs: 8
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 2],
    gamma: 0.1,
  }

model:
  name: 'modules.model_vision_embedding.BaseVision'
  checkpoint: ~
  vision: {
    loss_weight: 1.,
    embedding_loss_weight: 2.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
