global:
  name: train-embedding-align-35
  phase: train
  stage: pretrain-vision
  workdir: workdir
  seed: ~
 
dataset:
  train: {
    roots: ['data/training/scene/scene_train/',
            'data/training/scene/scene_test/',
            'data/training/web/web_train/',
            'data/training/web/web_test/'
            ],
    batch_size: 200
  }
  test: {
    roots: ['data/training/scene/scene_val/',
            'data/training/web/web_val/'],
    batch_size: 200
  }
  charset_path: data/new_benchmark.txt
  data_aug: True
  multiscales: False
  num_workers: 9

training:
  epochs: 8
  show_iters: 50
  eval_iters: 3000
  save_iters: 3000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 2],
    gamma: 0.1,
  }

model:
  name: 'modules.model_align_embedding-35.AlignModel'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: workdir/benchmark/best-benchmark.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
